// <auto-generated />
using System;
using AquaCareAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace AquaCare_Api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240606060256_Second")]
    partial class Second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AquaCare_Api.Model.Cidade", b =>
                {
                    b.Property<int>("CodigoCidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODIGO_CIDADE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoCidade"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("ESTADO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.HasKey("CodigoCidade");

                    b.ToTable("AQUACARE_CIDADE");
                });

            modelBuilder.Entity("AquaCare_Api.Model.Indicador", b =>
                {
                    b.Property<int>("CodigoIndicador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODIGO_INDICADOR");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoIndicador"));

                    b.Property<int>("CodigoLocal")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODIGO_LOCAL");

                    b.Property<DateTime>("DataHoraMedicao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_HORA_MEDICAO");

                    b.Property<int>("NivelColiformes")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NIVEL_COLIFORMES");

                    b.Property<decimal>("NivelOxigenioDissolvido")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("NIVEL_OXIGENIO_DISSOLVIDO");

                    b.Property<decimal>("NivelPH")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("NIVEL_PH");

                    b.Property<decimal>("NivelTemperatura")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("NIVEL_TEMPERATURA");

                    b.Property<decimal>("NivelTurbidez")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("NIVEL_TURBIDEZ");

                    b.HasKey("CodigoIndicador");

                    b.HasIndex("CodigoLocal");

                    b.ToTable("AQUACARE_INDICADOR");
                });

            modelBuilder.Entity("AquaCare_Api.Model.Local", b =>
                {
                    b.Property<int>("CodigoLocal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODIGO_LOCAL");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoLocal"));

                    b.Property<int>("CodigoCidade")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODIGO_CIDADE");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("LATITUDE");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("LONGITUDE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.HasKey("CodigoLocal");

                    b.ToTable("AQUACARE_LOCAL");
                });

            modelBuilder.Entity("AquaCare_Api.Model.Usuario", b =>
                {
                    b.Property<int>("CodigoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODIGO_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoUsuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("SENHA");

                    b.HasKey("CodigoUsuario");

                    b.ToTable("AQUACARE_USUARIO");
                });

            modelBuilder.Entity("AquaCare_Api.Model.Indicador", b =>
                {
                    b.HasOne("AquaCare_Api.Model.Local", "Local")
                        .WithMany()
                        .HasForeignKey("CodigoLocal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Local");
                });
#pragma warning restore 612, 618
        }
    }
}
